### ISSUE TITLE
Cannot create db with mysql

### ISSUE THREAD

**Issue by jm-73** [portfolioplus/pystockdb#59]
I am trying to setup a database. I use the example code on the github:

```
import logging
from pystockdb.tools.create import CreateAndFillDataBase

logger = logging.getLogger('test')
config = {
    'max_history': 1,
    'indices': ['DAX'],
    'currencies': ['EUR'],
    'db_args': {
        'provider': 'mysql',
        'host': 'mysql',
        'user': 'root',
        'passwd': 'example',
        'db': '',
        'create_db': True
    },
}
create = CreateAndFillDataBase(config, logger)
create.build()
```

I get this error message:
```
pony.orm.core.UnexpectedError:` Object Item[new:1] cannot be stored in the database. OperationalError: 1046 No database selected
```

I have tried to create a empty db manually, and played with the create_db-command, but to no success. Could anyone give me anythong on how to get the pystockdb to work with mysql or mariadb?

Kind regards J

**Comment by SlashGordon** [comment]
Hi Jm,

I think you should add a database name to the configuration. 

Greetings slash
